### ISSUE TITLE
Exception, No Module P256

### ISSUE THREAD

**Issue by martin-verlage** [AnTu2702/impfnachweisvalidierer#1]
Had little trouble setting up the code. Calling the command resulted in an exception:

.../impfnachweisvalidierer$ python3 hc1_verify.py --cert demo-dsc.crt --token "$(< demo-token.b45)"
Traceback (most recent call last):
  File "hc1_verify.py", line 7, in <module>
    from cose.curves import P256
ModuleNotFoundError: No module named 'cose.curves'

Had to correct in my downloaded files "from cose.curves import P256" to "from cose.keys.curves import P256". After that tweak the code did run like a charm.

**Comment by AnTu2702** [comment]
Thank you for reporting.

This is just caused by using a different version of cose, than that specified by requirements.txt.
I guess you installed the dependencies manually using e.g. "pip install cose".

Please consider using "pip install -r requirements.txt" instead.
But in general you are right to adapt to the newer version and I will consider updating as well... ;-)

Cheers, AnTu2702
